---

- name: Create a blueprint
  infra.osbuild.create_blueprint:
    dest: "{{ builder_blueprint_src_path }}"
    name: "{{ builder_blueprint_name }}"
    packages: "{{ builder_compose_pkgs }}"
    customizations: "{{ builder_compose_customizations }}"
  register: blueprint_output

- name: Push the blueprint into image builder
  infra.osbuild.push_blueprint:
    src: "{{ builder_blueprint_src_path }}"

- name: Start compose
  infra.osbuild.start_compose:
    blueprint: "{{ builder_blueprint_name }}"
    compose_type: "{{ builder_compose_type }}"
  register: compose_start_out

- name: Wait for compose to finish
  infra.osbuild.wait_compose:
    compose_id: "{{ compose_start_out['result']['build_id'] }}"

- name: Create tmp directory for blueprint
  ansible.builtin.file:
    path: "/tmp/{{ builder_blueprint_name }}"
    mode: 0755
    state: directory

- name: Export the compose artifact
  infra.osbuild.export_compose:
    compose_id: "{{ compose_start_out['result']['build_id'] }}"
    dest: "/tmp/{{ builder_blueprint_name }}/{{ builder_blueprint_name }}-{{ blueprint_output['current_version'] }}.{{ compose_start_out['result']['output_type'] }}" 