---

- name: Import pre-flight tasks
  ansible.builtin.import_tasks: pre-flight.yml

- name: Import tasks to build edge-commit and host
  ansible.builtin.include_role:
    name: infra.osbuild.builder

- name: Import tasks to build edge-installer
  ansible.builtin.import_tasks: build-edge-installer.yml

- name: Import post-flight tasks
  ansible.builtin.import_tasks: post-flight.yml
