---

# podman_load module has a bug
# - name: load in container image
#   containers.podman.podman_load:
#     input: "/tmp/{{ builder_blueprint_name }}/{{ builder_blueprint_name }}-{{ blueprint_output['current_version'] }}.{{ compose_start_out['result']['output_type'] }}"
#   register: loaded_image

- name: load in container image
  ansible.builtin.shell:
    cmd: cat "{{ loaded_image.stdout_lines[0].split(' ')[2] }}" | podman load
  register: loaded_image
  changed_when: false

- name: tag container image
  containers.podman.podman_tag:
    image: "{{ loaded_image.stdout_lines[0].split(' ')[2] }}"
    target_names:
      - "localhost/{{ builder_blueprint_name }}-container:{{ blueprint_output['current_version'] }}"

- name: run edge container
  containers.podman.podman_container:
    name: "{{ builder_blueprint_name }}-container"
    image:  "localhost/{{ builder_blueprint_name }}-container:{{ blueprint_output['current_version'] }}"
    ports:
      - 8080:8080
