---

builder_blueprint_name: test_blueprint
builder_blueprint_src_path: /tmp/blueprint.toml
builder_blueprint_distro_lower: "{{ ansible_distribution if not 'RedHat' else 'rhel' | lower }}"
builder_blueprint_ref: "{{ builder_blueprint_distro_lower }}/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/x86_64/edge"
builder_compose_type: edge-commit
builder_pub_key: "~/.ssh/id_rsa.pub"
builder_compose_pkgs:
  - "vim-enhanced"
  - "git"
  - "neovim"
builder_compose_customizations:
  user:
    name: "core"
    description: "test user"
    password: "openshift"
    key: "{{ builder_pub_key }}"
    groups: '["users", "wheel"]'
