# vim: ft=yaml.ansible
---
- name: Setup the builder and run a full demo
  hosts: builder
  vars:
    builder_blueprint_password: "extremelysecurepassword"
    builder_blueprint_name: end_to_end_demo
    builder_blueprint_src_path: /tmp/blueprint.toml
    builder_blueprint_distro_lower: "almalinux"
    builder_blueprint_ref: "{{ builder_blueprint_distro_lower }}/{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/x86_64/edge"
    builder_compose_type: edge-commit
    builder_pubkey_file: "/home/admiller/.ssh/id_rsa.pub"
    builder_compose_pkgs:
      - "vim-enhanced"
      - "git"
    builder_compose_customizations:
      user:
        name: "core"
        description: "test user"
        password: "{{ blueprint_password }}"
        key: "{{ slurp_out['content'] | b64decode }}"
        groups: '["users", "wheel"]'
  tasks:
    - name: Run the role
      ansible.builtin.import_role:
        name: infra.osbuild.setup_server

    - name: Slurp the pubkey
      ansible.builtin.slurp:
        src: "{{ builder_pubkey_file }}"
      delegate_to: localhost
      register: slurp_out

    - name: Run the role
      ansible.builtin.import_role:
        name: infra.osbuild.builder

- name: Run an update on the edge systems
  hosts: edge
  tasks:
    - name: Run rpm-ostree update
      ansible.builtin.command: /usr/bin/rpm-ostree upgrade
      changed_when: false
